[package]
name = "cmp3_proj"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
cpal = "0.15.3"
rand = "0.8"
slint = "1.9.2"
symphonia = { version = "0.5.4", features = ["mpa"] }

[build-dependencies]
slint-build = "1.9.2"
